// PM2配置文件
const enableBackgroundWorkers = process.env.ENABLE_BACKGROUND_WORKERS !== '0';
const enableAgenticPipeline = process.env.ENABLE_AGENTIC_PIPELINE ?? '1';
const openAgentRuntimeEnabled = process.env.OPEN_AGENT_RUNTIME_ENABLED ?? '1';
const cronEnv = {
  CONTENT_RADAR_CRON_TOKEN: 'life-kline-radar-local-2026',
  CONTENT_SCHEDULER_CRON_TOKEN: 'life-kline-scheduler-local-2026',
  CONTENT_GENERATION_CRON_TOKEN: 'life-kline-content-generation-local-2026',
  KNOWLEDGE_ACQUISITION_CRON_TOKEN: 'life-kline-knowledge-local-2026',
  REPORT_UPGRADE_CRON_TOKEN: 'life-kline-upgrade-local-2026',
  REPORT_MONTHLY_DIGEST_CRON_TOKEN: 'life-kline-monthly-digest-local-2026',
  EMAIL_RETRY_CRON_TOKEN: 'life-kline-email-retry-local-2026',
  TIMING_EMAIL_CRON_TOKEN: 'life-kline-timing-email-local-2026',
  USER_LIFECYCLE_EMAIL_CRON_TOKEN: 'life-kline-user-lifecycle-local-2026',
};

const nextApp = {
  name: 'life-kline-next',
  script: 'node_modules/next/dist/bin/next',
  args: 'start',
  cwd: '/home/life-kline-next',
  instances: 1,
  exec_mode: 'fork',
  env: {
    NODE_ENV: 'production',
    PORT: 3000,
    ENABLE_AGENTIC_PIPELINE: enableAgenticPipeline,
    DEFAULT_MODEL: 'gpt-5.2',
    OPEN_AGENT_RUNTIME_MODEL: 'gpt-5.2',
    CONTENT_GENERATION_MODEL: 'gpt-5.2',
    // v5-A5b (2026-05-09): ANALYZE 同步路径用 2 模型链，确保 weight 0.55+0.45 分到足够预算
    // auto 留给 content/agent 异步路径当第三兜底（它 67% 成功 + 21s，适合异步）
    MODEL_FALLBACK_CHAIN: 'grok-420-fast',
    REPORT_MODEL_FALLBACK_CHAIN: 'grok-420-fast',
    REPORT_NARRATIVE_MODEL_FALLBACK_CHAIN: 'grok-420-fast',
    CONTENT_GENERATION_MODEL_FALLBACK_CHAIN: 'grok-420-fast,auto',
    OPEN_AGENT_RUNTIME_ENABLED: openAgentRuntimeEnabled,
    // v5-A5d (2026-05-09): 熔断阈值放宽 — 之前 IMMEDIATE_OPEN=2 + CONSECUTIVE=3，并发 7 个 agent 同时失败时雪崩
    // 现在 main IMMEDIATE_OPEN=4 + CONSECUTIVE=5 + 冷却缩到 2 分钟，给系统更多自愈空间
    LLM_HEALTH_WINDOW_MINUTES: '15',
    LLM_CIRCUIT_OPEN_MIN_ATTEMPTS: '5',
    LLM_CIRCUIT_OPEN_FAILURE_RATE: '0.7',
    LLM_CIRCUIT_DEGRADE_FAILURE_RATE: '0.50',
    LLM_CIRCUIT_RECOVER_FAILURE_RATE: '0.30',
    LLM_CIRCUIT_OPEN_CONSECUTIVE_FAILURES: '5',
    LLM_CIRCUIT_IMMEDIATE_OPEN_CONSECUTIVE_FAILURES: '4',
    LLM_CIRCUIT_RECOVERY_SUCCESS_STREAK: '1',
    LLM_CIRCUIT_OPEN_COOLDOWN_MINUTES: '2',
    // v5-A4 (2026-05-08) 升级队列重试上限收紧：6 → 4
    // 配合 A1 删 'auto' + A2 熔断收紧，避免堆积 retry 风暴
    REPORT_UPGRADE_MAX_ATTEMPTS: '4',
    // 文章漏斗 v1（A 阶段）灰度开关 — A 阶段已 reload 上线 2026-05-10
    // 0 关闭 / 1 启用 inline+sticky+scrollDepth；NEXT_PUBLIC_* 是 build-time 内联，回滚需重 build
    NEXT_PUBLIC_ARTICLE_CTA_V1: process.env.NEXT_PUBLIC_ARTICLE_CTA_V1 || '1',
    // Sub-Spec C (2026-05-10) 命理时间提醒 cron token
    TIMING_EMAIL_CRON_TOKEN: 'life-kline-timing-email-local-2026',
    ...cronEnv,
    CONTENT_RADAR_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/radar/cron',
    CONTENT_RADAR_INTERVAL_MS: '2700000',
    CONTENT_RADAR_REQUEST_TIMEOUT_MS: '60000',
    CONTENT_RADAR_STARTUP_DELAY_MS: '15000',
    CONTENT_RADAR_RETRY_DELAY_MS: '60000',
    CONTENT_RADAR_AUTO_GENERATE: '0',
    CONTENT_RADAR_AUTO_PUBLISH: '0',
  },
  error_file: '/root/.pm2/logs/life-kline-next-error.log',
  out_file: '/root/.pm2/logs/life-kline-next-out.log',
  log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
  merge_logs: true,
  autorestart: true,
  max_restarts: 10,
  min_uptime: '10s',
  max_memory_restart: '1500M',
  watch: false,
  restart_delay: 4000,
};

const backgroundWorkers = enableBackgroundWorkers ? [
  {
    name: 'life-kline-email-retry',
    script: 'scripts/email-retry-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      EMAIL_RETRY_ENABLED: '1',
      EMAIL_RETRY_CRON_TOKEN: cronEnv.EMAIL_RETRY_CRON_TOKEN,
      EMAIL_RETRY_RUN_URL: 'http://127.0.0.1:3000/api/admin/email/retry/cron',
      EMAIL_RETRY_INTERVAL_MS: '120000',
      EMAIL_RETRY_BATCH_SIZE: '5',
      EMAIL_RETRY_MAX_ATTEMPTS: '4',
      EMAIL_RETRY_BASE_DELAY_MS: '300000',
      EMAIL_RETRY_REQUEST_TIMEOUT_MS: '60000',
      EMAIL_RETRY_STARTUP_DELAY_MS: '15000',
      EMAIL_RETRY_RETRY_DELAY_MS: '60000',
    },
    error_file: '/root/.pm2/logs/life-kline-email-retry-error.log',
    out_file: '/root/.pm2/logs/life-kline-email-retry-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-radar',
    script: 'scripts/content-radar-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      CONTENT_RADAR_ENABLED: '1',
      CONTENT_RADAR_CRON_TOKEN: cronEnv.CONTENT_RADAR_CRON_TOKEN,
      CONTENT_RADAR_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/radar/cron',
      CONTENT_RADAR_INTERVAL_MS: '2700000',
      CONTENT_RADAR_REQUEST_TIMEOUT_MS: '60000',
      CONTENT_RADAR_STARTUP_DELAY_MS: '15000',
      CONTENT_RADAR_RETRY_DELAY_MS: '60000',
      CONTENT_RADAR_AUTO_GENERATE: '0',
      CONTENT_RADAR_AUTO_PUBLISH: '0',
    },
    error_file: '/root/.pm2/logs/life-kline-radar-error.log',
    out_file: '/root/.pm2/logs/life-kline-radar-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-content-generation',
    script: 'scripts/content-generation-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      CONTENT_GENERATION_ENABLED: '1',
      CONTENT_GENERATION_CRON_TOKEN: cronEnv.CONTENT_GENERATION_CRON_TOKEN,
      CONTENT_GENERATION_JOB_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/generate/cron',
      CONTENT_GENERATION_JOB_INTERVAL_MS: '60000',
      CONTENT_GENERATION_JOB_REQUEST_TIMEOUT_MS: '900000',
      CONTENT_GENERATION_JOB_STARTUP_DELAY_MS: '15000',
      CONTENT_GENERATION_JOB_RETRY_DELAY_MS: '60000',
      CONTENT_GENERATION_JOB_MAX_ATTEMPTS: '3',
      CONTENT_GENERATION_JOB_BATCH_SIZE: '1',
    },
    error_file: '/root/.pm2/logs/life-kline-content-generation-error.log',
    out_file: '/root/.pm2/logs/life-kline-content-generation-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-scheduler',
    script: 'scripts/content-scheduler-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      CONTENT_SCHEDULER_ENABLED: '1',
      CONTENT_RADAR_CRON_TOKEN: cronEnv.CONTENT_RADAR_CRON_TOKEN,
      CONTENT_SCHEDULER_CRON_TOKEN: cronEnv.CONTENT_SCHEDULER_CRON_TOKEN,
      CONTENT_SCHEDULER_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/scheduler/cron',
      CONTENT_SCHEDULER_INTERVAL_MS: '1200000',
      CONTENT_SCHEDULER_REQUEST_TIMEOUT_MS: '900000',
      CONTENT_SCHEDULER_STARTUP_DELAY_MS: '20000',
      CONTENT_SCHEDULER_RETRY_DELAY_MS: '60000',
      CONTENT_SCHEDULER_TIMEZONE_OFFSET_MINUTES: '480',
      CONTENT_SCHEDULER_PUBLISH_HOURS: '10,15,20',
      CONTENT_SCHEDULER_DAILY_PUBLISH_LIMIT: '3',
      CONTENT_SCHEDULER_MIN_PUBLISH_GAP_MINUTES: '180',
      CONTENT_SCHEDULER_DRAFT_RESERVE_TARGET: '12',
      CONTENT_SCHEDULER_DRAFT_BATCH_SIZE: '3',
      CONTENT_SCHEDULER_GENERATE_COOLDOWN_MINUTES: '240',
      CONTENT_SCHEDULER_RADAR_REFRESH_MAX_AGE_HOURS: '4',
      CONTENT_SCHEDULER_ADAPTIVE_TYPE_WEIGHT: '10',
      CONTENT_SCHEDULER_ADAPTIVE_RADAR_SOURCE_WEIGHT: '14',
      CONTENT_SCHEDULER_ADAPTIVE_FRESHNESS_WEIGHT: '8',
    },
    error_file: '/root/.pm2/logs/life-kline-scheduler-error.log',
    out_file: '/root/.pm2/logs/life-kline-scheduler-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-knowledge',
    script: 'scripts/knowledge-acquisition-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      KNOWLEDGE_ACQUISITION_ENABLED: '1',
      KNOWLEDGE_ACQUISITION_CRON_TOKEN: cronEnv.KNOWLEDGE_ACQUISITION_CRON_TOKEN,
      KNOWLEDGE_ACQUISITION_RUN_URL: 'http://127.0.0.1:3000/api/admin/knowledge/sources/cron',
      KNOWLEDGE_ACQUISITION_INTERVAL_MS: '1800000',
      KNOWLEDGE_ACQUISITION_REQUEST_TIMEOUT_MS: '180000',
      KNOWLEDGE_ACQUISITION_STARTUP_DELAY_MS: '25000',
      KNOWLEDGE_ACQUISITION_RETRY_DELAY_MS: '60000',
      KNOWLEDGE_ACQUISITION_LOCK_TTL_MS: '2700000',
      KNOWLEDGE_ACQUISITION_REFRESH_RADAR: '1',
      KNOWLEDGE_ACQUISITION_CORE_LIMIT: '18',
      KNOWLEDGE_ACQUISITION_MAX_DOMAINS_PER_RUN: '3',
      KNOWLEDGE_ACQUISITION_SIGNAL_MIN_SCORE: '18',
      KNOWLEDGE_ACQUISITION_SIGNAL_PROMOTION_LIMIT: '10',
      KNOWLEDGE_ACQUISITION_RADAR_LIMIT_PER_SOURCE: '8',
      KNOWLEDGE_ACQUISITION_FOCUS_DOMAINS: 'metaphysics,psychology,philosophy,history,ai,statistics,programming,astrology,medicine',
      KNOWLEDGE_SYNTHESIS_AUTO_PUBLISH: '1',
      KNOWLEDGE_SYNTHESIS_PUBLISH_THRESHOLD: '78',
      KNOWLEDGE_SYNTHESIS_ALLOWED_TYPES: 'topic-overview,concept-glossary,book-path,book-ladder',
      KNOWLEDGE_SYNTHESIS_PUBLISH_BATCH_SIZE: '4',
    },
    error_file: '/root/.pm2/logs/life-kline-knowledge-error.log',
    out_file: '/root/.pm2/logs/life-kline-knowledge-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-report-upgrader',
    script: 'scripts/report-upgrade-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      REPORT_UPGRADE_ENABLED: '1',
      REPORT_UPGRADE_CRON_TOKEN: cronEnv.REPORT_UPGRADE_CRON_TOKEN,
      REPORT_UPGRADE_RUN_URL: 'http://127.0.0.1:3000/api/admin/report-upgrade/cron',
      REPORT_UPGRADE_INTERVAL_MS: '180000',
      REPORT_UPGRADE_BATCH_SIZE: '2',
      REPORT_UPGRADE_REQUEST_TIMEOUT_MS: '60000',
      REPORT_UPGRADE_STARTUP_DELAY_MS: '20000',
      REPORT_UPGRADE_RETRY_DELAY_MS: '60000',
      REPORT_MONTHLY_DIGEST_CRON_TOKEN: cronEnv.REPORT_MONTHLY_DIGEST_CRON_TOKEN,
      REPORT_MONTHLY_DIGEST_RUN_URL: 'http://127.0.0.1:3000/api/admin/report-monthly-digest/cron',
      REPORT_MONTHLY_DIGEST_INTERVAL_MS: '21600000',
      REPORT_MONTHLY_DIGEST_BATCH_SIZE: '20',
    },
    error_file: '/root/.pm2/logs/life-kline-report-upgrader-error.log',
    out_file: '/root/.pm2/logs/life-kline-report-upgrader-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-user-lifecycle-email',
    script: 'scripts/user-lifecycle-email-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      USER_LIFECYCLE_EMAIL_ENABLED: '1',
      USER_LIFECYCLE_EMAIL_CRON_TOKEN: cronEnv.USER_LIFECYCLE_EMAIL_CRON_TOKEN,
      USER_LIFECYCLE_EMAIL_RUN_URL: 'http://127.0.0.1:3000/api/admin/email/lifecycle/cron',
      USER_LIFECYCLE_EMAIL_INTERVAL_MS: '21600000',
      USER_LIFECYCLE_EMAIL_BATCH_SIZE: '25',
    },
    error_file: '/root/.pm2/logs/life-kline-user-lifecycle-email-error.log',
    out_file: '/root/.pm2/logs/life-kline-user-lifecycle-email-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-monthly-digest',
    script: 'scripts/report-monthly-digest-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      REPORT_MONTHLY_DIGEST_ENABLED: '1',
      REPORT_MONTHLY_DIGEST_CRON_TOKEN: cronEnv.REPORT_MONTHLY_DIGEST_CRON_TOKEN,
      REPORT_MONTHLY_DIGEST_RUN_URL: 'http://127.0.0.1:3000/api/admin/report-monthly-digest/cron',
      REPORT_MONTHLY_DIGEST_INTERVAL_MS: '21600000',
      REPORT_MONTHLY_DIGEST_BATCH_SIZE: '20',
      REPORT_MONTHLY_DIGEST_TIMEZONE_OFFSET_MINUTES: '480',
    },
    error_file: '/root/.pm2/logs/life-kline-monthly-digest-error.log',
    out_file: '/root/.pm2/logs/life-kline-monthly-digest-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
  {
    name: 'life-kline-timing-email',
    script: 'scripts/timing-email-daemon.js',
    cwd: '/home/life-kline-next',
    instances: 1,
    exec_mode: 'fork',
    env: {
      NODE_ENV: 'production',
      TIMING_EMAIL_CRON_TOKEN: cronEnv.TIMING_EMAIL_CRON_TOKEN,
      TIMING_EMAIL_RUN_URL: 'http://127.0.0.1:3000/api/admin/timing/email/cron?mode=auto',
      TIMING_EMAIL_INTERVAL_MS: '21600000',  // 6 小时
      TIMING_EMAIL_REQUEST_TIMEOUT_MS: '60000',
      TIMING_EMAIL_STARTUP_DELAY_MS: '30000',
      TIMING_EMAIL_RETRY_DELAY_MS: '60000',
    },
    error_file: '/root/.pm2/logs/life-kline-timing-email-error.log',
    out_file: '/root/.pm2/logs/life-kline-timing-email-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    max_restarts: 20,
    min_uptime: '10s',
    watch: false,
    restart_delay: 5000,
  },
] : [];

module.exports = {
  apps: [nextApp, ...backgroundWorkers],
};
