// PM2配置文件
module.exports = {
  apps: [
    {
      name: 'life-kline-next',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: '/home/life-kline-next',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        ENABLE_AGENTIC_PIPELINE: '1',
        DEFAULT_MODEL: 'gpt-5.2',
        MODEL_FALLBACK_CHAIN: 'gpt-5.2,grok-420-fast,auto',
        LLM_HEALTH_WINDOW_MINUTES: '30',
        LLM_CIRCUIT_OPEN_MIN_ATTEMPTS: '6',
        LLM_CIRCUIT_OPEN_FAILURE_RATE: '0.7',
        LLM_CIRCUIT_DEGRADE_FAILURE_RATE: '0.45',
        LLM_CIRCUIT_RECOVER_FAILURE_RATE: '0.35',
        LLM_CIRCUIT_OPEN_CONSECUTIVE_FAILURES: '4',
        LLM_CIRCUIT_RECOVERY_SUCCESS_STREAK: '2',
        LLM_CIRCUIT_OPEN_COOLDOWN_MINUTES: '8',
        CONTENT_RADAR_CRON_TOKEN: 'life-kline-radar-local-2026',
        CONTENT_RADAR_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/radar/cron',
        CONTENT_RADAR_INTERVAL_MS: '2700000',
        CONTENT_RADAR_AUTO_GENERATE: '0',
        CONTENT_RADAR_AUTO_PUBLISH: '0',
        CONTENT_SCHEDULER_CRON_TOKEN: 'life-kline-scheduler-local-2026',
        CONTENT_SCHEDULER_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/scheduler/cron',
        CONTENT_SCHEDULER_INTERVAL_MS: '1200000',
        CONTENT_SCHEDULER_TIMEZONE_OFFSET_MINUTES: '480',
        CONTENT_SCHEDULER_PUBLISH_HOURS: '10,15,20',
        CONTENT_SCHEDULER_DAILY_PUBLISH_LIMIT: '3',
        CONTENT_SCHEDULER_MIN_PUBLISH_GAP_MINUTES: '180',
        CONTENT_SCHEDULER_DRAFT_RESERVE_TARGET: '12',
        CONTENT_SCHEDULER_DRAFT_BATCH_SIZE: '3',
        CONTENT_SCHEDULER_GENERATE_COOLDOWN_MINUTES: '240',
        CONTENT_SCHEDULER_RADAR_REFRESH_MAX_AGE_HOURS: '4',
        CONTENT_SCHEDULER_ADAPTIVE_TYPE_WEIGHT: '10',
        CONTENT_SCHEDULER_ADAPTIVE_RADAR_SOURCE_WEIGHT: '14',
        CONTENT_SCHEDULER_ADAPTIVE_FRESHNESS_WEIGHT: '8',
      },
      error_file: '/root/.pm2/logs/life-kline-next-error.log',
      out_file: '/root/.pm2/logs/life-kline-next-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
      watch: false,
      restart_delay: 4000,
    },
    {
      name: 'life-kline-radar',
      script: 'scripts/content-radar-daemon.js',
      cwd: '/home/life-kline-next',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        CONTENT_RADAR_CRON_TOKEN: 'life-kline-radar-local-2026',
        CONTENT_RADAR_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/radar/cron',
        CONTENT_RADAR_INTERVAL_MS: '2700000',
        CONTENT_RADAR_AUTO_GENERATE: '0',
        CONTENT_RADAR_AUTO_PUBLISH: '0',
        CONTENT_SCHEDULER_CRON_TOKEN: 'life-kline-scheduler-local-2026',
        CONTENT_SCHEDULER_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/scheduler/cron',
        CONTENT_SCHEDULER_INTERVAL_MS: '1200000',
        CONTENT_SCHEDULER_TIMEZONE_OFFSET_MINUTES: '480',
        CONTENT_SCHEDULER_PUBLISH_HOURS: '10,15,20',
        CONTENT_SCHEDULER_DAILY_PUBLISH_LIMIT: '3',
        CONTENT_SCHEDULER_MIN_PUBLISH_GAP_MINUTES: '180',
        CONTENT_SCHEDULER_DRAFT_RESERVE_TARGET: '12',
        CONTENT_SCHEDULER_DRAFT_BATCH_SIZE: '3',
        CONTENT_SCHEDULER_GENERATE_COOLDOWN_MINUTES: '240',
        CONTENT_SCHEDULER_RADAR_REFRESH_MAX_AGE_HOURS: '4',
        CONTENT_SCHEDULER_ADAPTIVE_TYPE_WEIGHT: '10',
        CONTENT_SCHEDULER_ADAPTIVE_RADAR_SOURCE_WEIGHT: '14',
        CONTENT_SCHEDULER_ADAPTIVE_FRESHNESS_WEIGHT: '8',
      },
      error_file: '/root/.pm2/logs/life-kline-radar-error.log',
      out_file: '/root/.pm2/logs/life-kline-radar-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      watch: false,
      restart_delay: 5000,
    },
    {
      name: 'life-kline-scheduler',
      script: 'scripts/content-scheduler-daemon.js',
      cwd: '/home/life-kline-next',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        CONTENT_RADAR_CRON_TOKEN: 'life-kline-radar-local-2026',
        CONTENT_SCHEDULER_CRON_TOKEN: 'life-kline-scheduler-local-2026',
        CONTENT_SCHEDULER_RUN_URL: 'http://127.0.0.1:3000/api/admin/content/scheduler/cron',
        CONTENT_SCHEDULER_INTERVAL_MS: '1200000',
        CONTENT_SCHEDULER_TIMEZONE_OFFSET_MINUTES: '480',
        CONTENT_SCHEDULER_PUBLISH_HOURS: '10,15,20',
        CONTENT_SCHEDULER_DAILY_PUBLISH_LIMIT: '3',
        CONTENT_SCHEDULER_MIN_PUBLISH_GAP_MINUTES: '180',
        CONTENT_SCHEDULER_DRAFT_RESERVE_TARGET: '12',
        CONTENT_SCHEDULER_DRAFT_BATCH_SIZE: '3',
        CONTENT_SCHEDULER_GENERATE_COOLDOWN_MINUTES: '240',
        CONTENT_SCHEDULER_RADAR_REFRESH_MAX_AGE_HOURS: '4',
        CONTENT_SCHEDULER_ADAPTIVE_TYPE_WEIGHT: '10',
        CONTENT_SCHEDULER_ADAPTIVE_RADAR_SOURCE_WEIGHT: '14',
        CONTENT_SCHEDULER_ADAPTIVE_FRESHNESS_WEIGHT: '8',
      },
      error_file: '/root/.pm2/logs/life-kline-scheduler-error.log',
      out_file: '/root/.pm2/logs/life-kline-scheduler-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '10s',
      watch: false,
      restart_delay: 5000,
    },
  ],
};
