import type { AstroSignProfile, SignKey } from '@/lib/astro/types';

/** Civil tropical sun signs — content aligned with Life K-Line structure voice */
export const ASTRO_SIGNS: AstroSignProfile[] = [
  {
    key: 'aries',
    zh: '白羊座',
    en: 'Aries',
    symbol: '♈',
    element: '火',
    modality: '基本',
    ruler: '火星',
    start: '03-21',
    end: '04-19',
    keywords: ['开创', '直接', '速度', '勇气'],
    summary:
      '白羊以「先动再调」为节奏：目标清晰时爆发力强，适合开局与破局。内核是推进欲，不是莽撞本身。',
    strengths: ['启动快，敢承担第一棒', '冲突中仍能说清立场', '失败后重启成本低'],
    watchouts: ['未确认约束就全开油门', '把速度当成唯一价值', '对慢节奏伙伴缺乏耐心'],
    career: '适合开拓、销售冲锋、项目启动、危机响应；长期深耕需配固定或土象协作。',
    relationship: '直球表达讨喜，也容易踩边界；关系里宜把「冲动」翻译成「清晰请求」。',
    worldYiBridge:
      '世界易视角：白羊对应「进入窗口」的火性开启。先看阶段是否允许冲，再看组织结构是否接得住。',
    dailyRhythm: '黄历宜「开市、出行、动土」类行动日更合拍；忌日宜收敛冲突性决策。',
    pairsWell: ['leo', 'sagittarius', 'gemini'],
    needsWork: ['cancer', 'capricorn'],
  },
  {
    key: 'taurus',
    zh: '金牛座',
    en: 'Taurus',
    symbol: '♉',
    element: '土',
    modality: '固定',
    ruler: '金星',
    start: '04-20',
    end: '05-20',
    keywords: ['稳定', '感官', '持有', '节奏'],
    summary:
      '金牛以「可感知的积累」定义安全感：慢，但是真的落地。适合把愿景变成资产与习惯。',
    strengths: ['执行耐力强', '审美与价值判断稳', '守成与复利意识'],
    watchouts: ['变化窗口来了仍死守旧路径', '把舒适区误认为终点', '金钱/身体议题过度黏着'],
    career: '适合产品打磨、财务稳健、品牌质感、长期客户；高速 pivot 需外力拉动。',
    relationship: '忠诚可靠，表达偏行动不偏口号；对方需理解「慢热」不是冷淡。',
    worldYiBridge:
      '世界易视角：金牛对应财富「保留结构」。先问能守住什么，再问扩张是否过早。',
    dailyRhythm: '宜「纳财、安床、立券」类日子做资产与习惯建设；忌日少做冲动大额支出。',
    pairsWell: ['virgo', 'capricorn', 'cancer'],
    needsWork: ['aquarius', 'leo'],
  },
  {
    key: 'gemini',
    zh: '双子座',
    en: 'Gemini',
    symbol: '♊',
    element: '风',
    modality: '变动',
    ruler: '水星',
    start: '05-21',
    end: '06-21',
    keywords: ['信息', '连接', '灵活', '表达'],
    summary:
      '双子靠信息差与话术网络推进：多线程、好奇、能翻译复杂为可传播。风险是浅尝辄止。',
    strengths: ['学习与切换快', '社交节点多', '善于包装与沟通'],
    watchouts: ['承诺过多交付不足', '用新刺激逃避深耕', '情绪被信息流绑架'],
    career: '适合媒体、产品运营、商务对接、教研传播；深度专业需固定辅星或团队补位。',
    relationship: '有趣是王牌，稳定感靠「可验证小承诺」建立，而非口号式专一。',
    worldYiBridge:
      '世界易视角：双子对应「信息—协作—节奏」三角。关系与事业卡点常出在沟通边界不清。',
    dailyRhythm: '宜「会亲友、订盟、开市」信息日；忌日少签无法兑现的口头承诺。',
    pairsWell: ['libra', 'aquarius', 'aries'],
    needsWork: ['sagittarius', 'pisces'],
  },
  {
    key: 'cancer',
    zh: '巨蟹座',
    en: 'Cancer',
    symbol: '♋',
    element: '水',
    modality: '基本',
    ruler: '月亮',
    start: '06-22',
    end: '07-22',
    keywords: ['照护', '记忆', '归属', '情绪潮汐'],
    summary:
      '巨蟹以归属与情绪安全为底座：对家庭、团队「家」的感觉极敏感。能量潮汐明显。',
    strengths: ['共情与照顾力', '记忆与线索完整', '护航型领导'],
    watchouts: ['情绪吞没决策', '过度防卫或情绪勒索', '把过去未愈投射到当下'],
    career: '适合人力、客服、内容情感向、餐饮/居住相关；高压冷血环境消耗大。',
    relationship: '需要被「放在心上」的证据；边界清晰后反而更温柔稳定。',
    worldYiBridge:
      '世界易视角：巨蟹对应家庭与关系「边界—照护」轴。先问谁在消耗谁，再谈合不合。',
    dailyRhythm: '宜「入宅、安香、会亲友」；忌日少做家庭冲突升级的硬对话。',
    pairsWell: ['scorpio', 'pisces', 'taurus'],
    needsWork: ['aries', 'libra'],
  },
  {
    key: 'leo',
    zh: '狮子座',
    en: 'Leo',
    symbol: '♌',
    element: '火',
    modality: '固定',
    ruler: '太阳',
    start: '07-23',
    end: '08-22',
    keywords: ['舞台', '表达', '荣誉', '慷慨'],
    summary:
      '狮子把生命做成可见的作品：需要认可，也愿意大方回馈。核心是尊严与创造欲。',
    strengths: ['感染力与号召力', '对品质有标准', '愿意扛名与责任'],
    watchouts: ['面子绑架判断', '忽视团队背板功劳', '低谷期过度戏剧化'],
    career: '适合品牌、演艺、教育主讲、管理前台；后台长周期需土象协作。',
    relationship: '渴望被看见；健康关系是互相加冕，而不是互相争夺聚光灯。',
    worldYiBridge:
      '世界易视角：狮子对应「角色可见度」。事业问题常是角色与舞台是否匹配，而非只缺努力。',
    dailyRhythm: '宜「开市、嫁娶、祈福」高光日；忌日收敛争面子的公开冲突。',
    pairsWell: ['aries', 'sagittarius', 'libra'],
    needsWork: ['taurus', 'scorpio'],
  },
  {
    key: 'virgo',
    zh: '处女座',
    en: 'Virgo',
    symbol: '♍',
    element: '土',
    modality: '变动',
    ruler: '水星',
    start: '08-23',
    end: '09-22',
    keywords: ['优化', '细节', '服务', '秩序'],
    summary:
      '处女以「把东西变好一点」获得安全感：系统、清单、可改进点。风险是完美主义瘫痪。',
    strengths: ['诊断问题精准', '流程与质控', '务实的助人'],
    watchouts: ['只见缺陷不见整体', '用忙碌逃避情感', '对自己苛责外溢到他人'],
    career: '适合运营、分析、医疗健康支持、编辑、工程质控；战略叙事需风/火补位。',
    relationship: '爱用帮忙表达；对方需要把「批评」听成「在乎」，自己也需练温柔反馈。',
    worldYiBridge:
      '世界易视角：处女对应「动作可验证」。健康与事业都适合拆成检查清单，而非情绪定论。',
    dailyRhythm: '宜「修造、扫舍、求医」整理日；忌日少对亲密关系做过度检讨清单。',
    pairsWell: ['taurus', 'capricorn', 'cancer'],
    needsWork: ['sagittarius', 'pisces'],
  },
  {
    key: 'libra',
    zh: '天秤座',
    en: 'Libra',
    symbol: '♎',
    element: '风',
    modality: '基本',
    ruler: '金星',
    start: '09-23',
    end: '10-23',
    keywords: ['平衡', '审美', '协商', '关系'],
    summary:
      '天秤在关系与美学中找平衡：怕一边倒，也怕孤独决策。强项是协调与品味。',
    strengths: ['谈判与调和', '审美与公关', '能看见多方利益'],
    watchouts: ['犹豫不决拖成内耗', '讨好后反噬', '用表面和谐掩盖真实冲突'],
    career: '适合法务协调、设计、商务、公关、HR；需要明确拍板权时要补基本宫火土。',
    relationship: '配对是主课题；健康关系要能「不和也安全」，而非永远和气。',
    worldYiBridge:
      '世界易视角：天秤对应关系「节奏与边界」。合不合之前，先看交换是否对等。',
    dailyRhythm: '宜「订盟、嫁娶、会亲友」；忌日少做一边倒讨好式妥协。',
    pairsWell: ['gemini', 'aquarius', 'leo'],
    needsWork: ['cancer', 'capricorn'],
  },
  {
    key: 'scorpio',
    zh: '天蝎座',
    en: 'Scorpio',
    symbol: '♏',
    element: '水',
    modality: '固定',
    ruler: '冥王/火星',
    start: '10-24',
    end: '11-22',
    keywords: ['穿透', '深度', '转化', '边界'],
    summary:
      '天蝎看见表层下的权力与欲望：要么深潜转化，要么僵持控制。强度是武器也是代价。',
    strengths: ['洞察动机', '危机中的冷静狠劲', '忠诚于真正信任的人'],
    watchouts: ['控制与报复循环', '把一切关系做成审讯', '秘密过多导致孤立'],
    career: '适合调研、风控、心理、投资深研、危机公关；表层社交岗易耗能。',
    relationship: '要绝对信任或干脆退出；宜用「透明协议」替代猜忌。',
    worldYiBridge:
      '世界易视角：天蝎对应「结构张力与转化」。时代压力大时，先止损再谈深度绑定。',
    dailyRhythm: '宜「破土、安葬、解除」转化类；忌日少做报复性重大决定。',
    pairsWell: ['cancer', 'pisces', 'virgo'],
    needsWork: ['leo', 'aquarius'],
  },
  {
    key: 'sagittarius',
    zh: '射手座',
    en: 'Sagittarius',
    symbol: '♐',
    element: '火',
    modality: '变动',
    ruler: '木星',
    start: '11-23',
    end: '12-21',
    keywords: ['视野', '意义', '远方', '诚实'],
    summary:
      '射手追求意义与地图外的路：哲学、旅行、跨境、教学。怕被小框困住。',
    strengths: ['乐观扩张', '跨文化翻译', '直言不讳的诚实'],
    watchouts: ['承诺过大无法落地', '用「自由」逃避亲密责任', '道德优越感'],
    career: '适合教育、跨境、出版、品牌故事、运动户外；细节交付需处女/金牛协作。',
    relationship: '需要呼吸空间；可持续关系是「共同远方」而非日日捆绑。',
    worldYiBridge:
      '世界易视角：射手对应迁移与认知扩张。城市/国家主题与跨境案例高度相关。',
    dailyRhythm: '宜「出行、赴任、开市」；忌日少做毫无缓冲的远途承诺。',
    pairsWell: ['aries', 'leo', 'aquarius'],
    needsWork: ['virgo', 'gemini'],
  },
  {
    key: 'capricorn',
    zh: '摩羯座',
    en: 'Capricorn',
    symbol: '♑',
    element: '土',
    modality: '基本',
    ruler: '土星',
    start: '12-22',
    end: '01-19',
    keywords: ['结构', '责任', '攀登', '时间'],
    summary:
      '摩羯用时间换权威：台阶式上升，尊重规则也善用规则。代价是情感账可能后付。',
    strengths: ['长期规划', '承压与纪律', '把理想做成组织'],
    watchouts: ['只认结果不认过程人', '情感延期支付', '把自我价值绑在 rank 上'],
    career: '适合管理、政务、财务、基建、严肃品牌；创意发散岗需火风补位。',
    relationship: '用可靠证明爱；对方要主动要柔软，自己也要练习非绩效的亲密。',
    worldYiBridge:
      '世界易视角：摩羯对应「阶段—组织—责任」。事业窗口判断与时代天时高度同频。',
    dailyRhythm: '宜「赴任、立券、修造」；忌日少做只为面子的攀比式消费。',
    pairsWell: ['taurus', 'virgo', 'scorpio'],
    needsWork: ['aries', 'libra'],
  },
  {
    key: 'aquarius',
    zh: '水瓶座',
    en: 'Aquarius',
    symbol: '♒',
    element: '风',
    modality: '固定',
    ruler: '天王/土星',
    start: '01-20',
    end: '02-18',
    keywords: ['系统', '社群', '未来', '独立'],
    summary:
      '水瓶为理念与网络而活：疏离感是盔甲，也是观察优势。适合改规则的人。',
    strengths: ['系统思维', '社群组织', '不从众的清醒'],
    watchouts: ['情感抽离过度', '为反对而反对', '理想压垮日常关系'],
    career: '适合科技、社群产品、研究、公益、非常规创业；人情世故岗需水象补位。',
    relationship: '要友谊式亲密；高压占有会触发逃离。',
    worldYiBridge:
      '世界易视角：水瓶对应「结构重写与网络」。全球对照、城市矩阵与其气质同频。',
    dailyRhythm: '宜「会亲友、开市、订盟」网络日；忌日少公开站队撕破。',
    pairsWell: ['gemini', 'libra', 'sagittarius'],
    needsWork: ['taurus', 'scorpio'],
  },
  {
    key: 'pisces',
    zh: '双鱼座',
    en: 'Pisces',
    symbol: '♓',
    element: '水',
    modality: '变动',
    ruler: '海王/木星',
    start: '02-19',
    end: '03-20',
    keywords: ['想象', '共情', '溶解', '灵性'],
    summary:
      '双鱼边界薄、感知强：艺术与慈悲是通道，逃避与自我牺牲是陷阱。',
    strengths: ['创造力与共情', '看见无形情绪', '融合多元叙事'],
    watchouts: ['现实逃避', '拯救者陷阱', '边界溶解后的怨恨'],
    career: '适合艺术、疗愈支持、影视、品牌情感；硬核 KPI 环境需土象护栏。',
    relationship: '灵魂感很强；可持续靠「小而清晰的约定」，而非无限牺牲。',
    worldYiBridge:
      '世界易视角：双鱼对应「叙事与情绪场」。时代叙事、集体情绪下更要守结构边界。',
    dailyRhythm: '宜「祭祀、祈福、沐浴」收敛日；忌日少做边界模糊的金钱人情债。',
    pairsWell: ['cancer', 'scorpio', 'taurus'],
    needsWork: ['gemini', 'sagittarius'],
  },
];

export const SIGN_BY_KEY: Record<SignKey, AstroSignProfile> = ASTRO_SIGNS.reduce(
  (acc, s) => {
    acc[s.key] = s;
    return acc;
  },
  {} as Record<SignKey, AstroSignProfile>,
);

export function getSignByKey(key: string | null | undefined): AstroSignProfile | null {
  if (!key) return null;
  return SIGN_BY_KEY[key as SignKey] || null;
}

export function getSignByZh(zh: string | null | undefined): AstroSignProfile | null {
  if (!zh) return null;
  return ASTRO_SIGNS.find((s) => s.zh === zh || s.zh.replace('座', '') === zh.replace('座', '')) || null;
}
