/**
 * Page / report illustration catalog.
 * src is public path under /images/page-illustrations/ after publish.
 */

export type PageIllustRole =
  | 'cover'
  | 'structure'
  | 'timing'
  | 'action'
  | 'risk'
  | 'summary';

export type PageIllustrationEntry = {
  id: string;
  surfaces: string[];
  role: PageIllustRole;
  title: string;
  caption: string;
  alt: string;
  filename: string;
  aspectRatio: '16:9' | '3:2' | '1:1';
  /** Prompt body without style suffix */
  prompt: string;
  /**
   * Generation routing for inping API:
   * - complex → gpt-image-2 (multi-panel, Chinese labels)
   * - simple  → z-image-turbo (icons / tiny assets, ~20× faster)
   */
  complexity?: 'complex' | 'simple';
  reportCiteKeys?: string[];
  tags: string[];
  /** Set true after asset exists in public/ */
  ready: boolean;
  width?: number;
  height?: number;
};

export const PAGE_ILLUST_STYLE_SUFFIX = [
  'Editorial product diagram for Life K-Line (人生K线), Chinese decision-support app.',
  'Clean Linear UI aesthetic, soft paper background, muted ink blue accents, geometric diagrams,',
  'minimal icons, high readability, no crystal ball, no horror, no superstition marketing slogans,',
  'no watermark, no low-quality stock photo. Clear Chinese labels where text appears.',
].join(' ');

export const PAGE_ILLUSTRATION_CATALOG: PageIllustrationEntry[] = [
  {
    id: 'PI-HOME-01',
    surfaces: ['home/workspace', 'analyze/workspace'],
    role: 'cover',
    title: '从生辰到可执行判断',
    caption: '排盘 → 报告结构 → 顾问开场 → 验证回访',
    alt: '人生K线从排盘到报告顾问验证的路径示意图',
    filename: 'home-path-from-birth-to-action.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Horizontal product journey diagram: four calm cards connected by arrows — 填生辰, 读报告, 顾问开场, 事件验证. Soft paper background, blue ink accents, minimal icons of calendar birth form, document report, chat bubble, checklist. Chinese labels only.',
    reportCiteKeys: ['cover'],
    tags: ['首页', '排盘', '路径'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-REPORT-READ-01',
    surfaces: ['docs/read-first-report', 'report/cover'],
    role: 'structure',
    title: '第一份报告怎么读',
    caption: '先结论与窗口，再看结构与风险',
    alt: '第一份命理报告阅读顺序图：结论窗口结构风险',
    filename: 'report-first-reading-path.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Infographic map of reading a fortune report: numbered steps 1 结论 2 时间窗口 3 结构依据 4 风险 5 验证点. Clean layered document illustration, blue accent numbers, paper texture, Chinese UI style.',
    reportCiteKeys: ['cover', 'reading-path'],
    tags: ['报告', '阅读'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-REPORT-TIMING-01',
    surfaces: ['report/timing', 'dimensions/fortune-rhythm'],
    role: 'timing',
    title: '大运与流年窗口',
    caption: '阶段节奏：有利窗 / 谨慎窗，而不是绝对吉凶',
    alt: '大运流年时间轴示意：有利窗口与谨慎窗口',
    filename: 'report-dayun-liunian-windows.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Timeline diagram of life phases (大运) with smaller yearly marks (流年). Soft green zones labeled 有利窗 and amber zones 谨慎窗. Minimal K-line rhythm below. Educational, not fatalistic. Chinese labels.',
    reportCiteKeys: ['dayun', 'timing'],
    tags: ['大运', '流年', '窗口'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-REPORT-DECISION-01',
    surfaces: ['report/decision', 'chat/structure'],
    role: 'action',
    title: '决策闭环：依据→结论→动作→验证',
    caption: '今天 / 7 天 / 30 天 三步可执行',
    alt: '命理决策闭环图：判断依据当前结论阶段动作风险验证点',
    filename: 'decision-loop-basis-action-verify.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Five connected modules in a clean flow: 判断依据, 当前结论, 阶段动作 (今天 7天 30天), 风险提醒, 验证点. Messenger/product UI inspired cards, blue accent, Chinese labels, decision product diagram.',
    reportCiteKeys: ['decision-loop'],
    tags: ['决策', '验证', '动作'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-YONGSHEN-01',
    surfaces: ['report/structure', 'teachers/overview'],
    role: 'structure',
    title: '日主与用神喜忌（示意）',
    caption: '结构锚点：日主、用神、忌神 — 以报告锁定为准',
    alt: '日主用神忌神结构示意教学图',
    filename: 'structure-daymaster-yongshen.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Abstract educational diagram of Chinese metaphysics structure: center node 日主, supporting nodes 用神, caution nodes 忌神, surrounding five-element cycle lightly drawn. Soft colors, schematic not portrait, Chinese labels, textbook clarity.',
    reportCiteKeys: ['yongshen', 'structure'],
    tags: ['日主', '用神', '结构'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-CHAT-OPENING-01',
    surfaces: ['chat/opening', 'teachers/hub'],
    role: 'summary',
    title: '顾问开场：老师先说，一点即发',
    caption: '不预填长问题；议题芯片 + 一键开口',
    alt: '顾问开场对话界面示意图：开场气泡与一键开口',
    filename: 'chat-consultant-opening.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Clean mobile chat UI mock: left gray bubble 顾问开场, topic chips, one large blue primary button 一键开口. Linear minimal interface, Chinese UI text, no clutter, product screenshot illustration style.',
    reportCiteKeys: [],
    tags: ['对话', '开场', '老师'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-EVENTS-01',
    surfaces: ['events/validation', 'predictions/revisit'],
    role: 'action',
    title: '事件验证闭环',
    caption: '记录 → 应验/偏差 → 带报告回聊',
    alt: '事件验证闭环：记录应验偏差回聊示意图',
    filename: 'events-validation-loop.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Circular loop diagram with four stations: 记录事件, 到期回访, 应验或偏差, 顾问回聊纠偏. Calm checklist aesthetic, blue and soft green, Chinese labels, product education.',
    reportCiteKeys: ['validation'],
    tags: ['事件', '验证', '回访'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-BOUNDARY-01',
    surfaces: ['boundary/not-fatalism', 'docs/read-first-report'],
    role: 'risk',
    title: '判断边界：参考不是定论',
    caption: '不恐吓、不绝对化；医疗法律投资需专业意见',
    alt: '命理判断边界说明：参考框架非宿命定论',
    filename: 'boundary-not-fatalism.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Two-column comparison diagram: left 可做 (结构参考 窗口节奏 可验证动作), right 不做 (恐吓 绝对命运 替代医疗法律投资). Soft warning amber on right, calm blue on left, Chinese labels, ethical product illustration.',
    reportCiteKeys: ['boundary'],
    tags: ['边界', '风险', '克制'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-TOOLS-01',
    surfaces: ['tools/hub', 'home/workspace', 'dimensions/hub'],
    role: 'action',
    title: '工具：把大问题拆成可测小问题',
    caption: '单项工具 → 报告深问 → 回访',
    alt: '工具中心问题拆解与报告衔接示意图',
    filename: 'tools-problem-breakdown.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Matrix of small tool cards around a central report document. Arrows from fuzzy question cloud into clear tool cards then into report. Minimal product diagram, Chinese labels 工具 报告 回访.',
    reportCiteKeys: [],
    tags: ['工具', '拆解', '十维度'],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: 'PI-TEACHERS-01',
    surfaces: ['teachers/hub', 'chat/opening'],
    role: 'cover',
    title: '一位老师专一事',
    caption: '总览 / 事业 / 财务 / 关系 / 时机… 按意图开场',
    alt: '多位顾问老师按议题分工示意图',
    filename: 'teachers-roles-map.jpg',
    aspectRatio: '16:9',
    complexity: 'complex',
    prompt:
      'Horizontal set of six minimal advisor cards with Chinese titles 总览老师 事业老师 财务老师 关系老师 时机老师 实践老师, each with one-line duty. Clean Linear list aesthetic, no realistic faces, abstract avatars as simple geometric shapes.',
    reportCiteKeys: [],
    tags: ['老师', '顾问'],
    ready: true,
    width: 1600,
    height: 900,
  },

  // --- Wave B/C expansion (batch gen) ---
  {
    id: "PI-DOCS-HUB-01",
    surfaces: ["docs/hub", "docs/read-first-report"],
    role: "structure",
    title: "方法先于结论",
    caption: "生辰填写 → 真太阳时 → 报告读法",
    alt: "文档中心方法路径：生辰真太阳时报告读法",
    filename: "docs-method-before-conclusion.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Three-step educational path diagram for a Chinese decision-support app: 1 填写生辰 2 理解真太阳时 3 按顺序读报告. Clean Linear cards, soft paper background, muted ink blue, numbered steps, no superstition imagery.",
    reportCiteKeys: ["reading-path"],
    tags: ["文档", "方法"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-PREDICTIONS-01",
    surfaces: ["predictions/revisit", "events/validation"],
    role: "timing",
    title: "预测回访：对照现实校准",
    caption: "时间窗到期 → 命中/部分/未命中 → 带偏差回聊",
    alt: "预测回访流程：到期反馈校准",
    filename: "predictions-revisit-feedback.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Product timeline: prediction card with time window, calendar mark 到期, three feedback chips 命中 部分 未命中, arrow to chat with advisor. Calm educational diagram, Chinese labels, Linear UI, soft paper.",
    reportCiteKeys: ["validation"],
    tags: ["预测", "回访"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-HEHUN-01",
    surfaces: ["hehun/hub", "dimensions/marriage"],
    role: "structure",
    title: "合婚：双盘对照",
    caption: "日主互动 · 用忌互补 · 不是简单合不合",
    alt: "合婚双盘对照示意：两人结构并排",
    filename: "hehun-dual-chart-compare.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Two calm side-by-side profile cards labeled 甲方 乙方, connecting lines for 日主互动 and 用忌互补, center label 对照而非定论. Soft paper, ink blue, geometric, Chinese labels, educational marriage chart comparison not romance stock photo.",
    reportCiteKeys: [],
    tags: ["合婚", "关系"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-MEMBERSHIP-01",
    surfaces: ["membership/hub"],
    role: "summary",
    title: "会员：完整报告与回看",
    caption: "结构全文 · 窗口详解 · 邮箱保存 · 持续回访",
    alt: "会员权益结构：报告回看回访",
    filename: "membership-report-access.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Clean product benefits diagram with four quiet cards: 完整报告, 窗口详解, 邮箱保存, 预测回访. Not flashy sales, Linear aesthetic, paper background, Chinese labels, membership as research access not destiny guarantee.",
    reportCiteKeys: [],
    tags: ["会员", "权益"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-PROFILE-01",
    surfaces: ["profile/hub", "profile/progressive"],
    role: "action",
    title: "资料越完整，判断越稳",
    caption: "生辰 → 情境 → 事件 → 偏好，渐进补全",
    alt: "渐进式资料完善路径示意图",
    filename: "profile-progressive-fill.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Progressive profile ladder diagram: steps 生辰基础, 当前情境, 关键事件, 决策偏好 with progress bar. Minimal Linear forms aesthetic, soft paper, Chinese labels, calm product education.",
    reportCiteKeys: [],
    tags: ["资料", "档案"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-KLINE-01",
    surfaces: ["report/kline", "home/workspace", "analyze/workspace"],
    role: "timing",
    title: "人生K线：节奏而不是宿命",
    caption: "大运段落 + 流年波动 + 可执行窗口",
    alt: "人生K线节奏示意：阶段与波动",
    filename: "life-kline-rhythm-concept.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Elegant abstract life K-line chart: gentle candlestick-like rhythm over multi-year axis, annotated 大运段落 and 流年波动, soft green favorable windows. Educational finance-chart aesthetic mixed with calm life planning, Chinese labels, no horror fate imagery.",
    reportCiteKeys: ["dayun", "timing"],
    tags: ["K线", "节奏"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-FIVE-ELEMENTS-01",
    surfaces: ["report/structure", "learn/hub", "knowledge/hub"],
    role: "structure",
    title: "五行生克（教学示意）",
    caption: "结构关系示意，具体以本盘报告锁定为准",
    alt: "五行生克循环教学示意图",
    filename: "five-elements-cycle-edu.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Clean educational five-elements cycle diagram 木 火 土 金 水 with generation arrows and control dashed arrows. Soft pastel geometric nodes, textbook clarity, Chinese characters, paper background, not mystical altar art.",
    reportCiteKeys: ["structure"],
    tags: ["五行", "结构"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-CHAT-STRUCTURE-01",
    surfaces: ["chat/structure", "chat/opening"],
    role: "action",
    title: "顾问回答五段结构",
    caption: "判断依据 · 结论 · 动作 · 风险 · 验证点",
    alt: "聊天回答五段结构卡片示意",
    filename: "chat-answer-five-parts.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Messenger-style answer card broken into five numbered sections: 1 判断依据 2 当前结论 3 阶段动作 4 风险提醒 5 验证点. Clean product UI illustration, Chinese text, Linear minimal, soft paper background.",
    reportCiteKeys: ["decision-loop"],
    tags: ["对话", "结构"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-REPORT-RISK-01",
    surfaces: ["report/risk", "report/decision"],
    role: "risk",
    title: "风险提醒怎么读",
    caption: "指出脆弱面与回撤条件，不是恐吓",
    alt: "报告风险提醒阅读示意图",
    filename: "report-risk-reading.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Soft amber callout cards labeled 脆弱面 回撤条件 需要验证, beside a calm document. Educational risk framing for decision support, Chinese labels, no horror, Linear product diagram.",
    reportCiteKeys: ["boundary"],
    tags: ["风险", "报告"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-REPORT-ACTION-01",
    surfaces: ["report/action", "report/decision"],
    role: "action",
    title: "阶段动作：今天 / 7天 / 30天",
    caption: "把结论拆成可执行节奏",
    alt: "报告阶段动作三时间框示意图",
    filename: "report-action-today-7-30.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Three horizontal time boxes labeled 今天 7天 30天 with simple checklist icons inside each. Clean Linear task board aesthetic, Chinese labels, paper background, action-oriented product diagram.",
    reportCiteKeys: ["decision-loop"],
    tags: ["动作", "报告"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-ANNUAL-01",
    surfaces: ["annual-review/hub", "predictions/revisit"],
    role: "summary",
    title: "年度复盘闭环",
    caption: "回顾窗口 → 对照事件 → 调整下一年动作",
    alt: "年度复盘三步闭环图",
    filename: "annual-review-loop.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Circular year-in-review diagram: 回顾时间窗, 对照真实事件, 写下一年动作. Calm calendar and checklist motifs, Chinese labels, soft paper, Linear product education.",
    reportCiteKeys: ["validation"],
    tags: ["复盘", "年度"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-LEARN-01",
    surfaces: ["learn/hub", "knowledge/hub"],
    role: "cover",
    title: "学习路径：专题可读",
    caption: "入门 → 结构 → 事业财运关系 → 应用",
    alt: "学习专题路径地图示意图",
    filename: "learn-track-map.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Learning track map with connected nodes: 入门 结构 事业 财富 关系 健康 迁移 应用. Soft geometric path, Chinese labels, Linear education product aesthetic, paper background.",
    reportCiteKeys: [],
    tags: ["学习", "专题"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-KNOWLEDGE-01",
    surfaces: ["knowledge/hub", "docs/hub"],
    role: "structure",
    title: "知识库：概念可回查",
    caption: "术语 → 例子 → 回到本盘报告",
    alt: "知识库概念回查路径图",
    filename: "knowledge-lookup-loop.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Three-step knowledge loop: 查术语, 看例子, 回报告对照. Book and document icons minimal, Chinese labels, calm library aesthetic for product, not mystic.",
    reportCiteKeys: [],
    tags: ["知识库"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-MOVEMENT-01",
    surfaces: ["movement/hub", "teachers/geo"],
    role: "action",
    title: "迁移与环境层",
    caption: "结构不变，环境可观察；迁移是变量不是仙丹",
    alt: "迁移环境层决策示意",
    filename: "movement-environment-layer.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Diagram with base layer 本盘结构 and overlay layer 城市环境/迁移选项. Two city pins connected by dashed arrow, Chinese labels 结构锚点 环境变量. Educational geo decision support, Linear style, no destiny magic.",
    reportCiteKeys: [],
    tags: ["迁移", "环境"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-SOLAR-TIME-01",
    surfaces: ["docs/solar-time", "docs/hub", "analyze/workspace"],
    role: "structure",
    title: "真太阳时为什么重要",
    caption: "经度与时差影响时柱精度",
    alt: "真太阳时与出生地经度关系示意图",
    filename: "solar-time-longitude.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Educational diagram: clock, map longitude line, birth form fields 出生地 钟表时间 真太阳时. Arrows showing correction. Chinese labels, calm science-education style, Linear product, soft paper.",
    reportCiteKeys: [],
    tags: ["真太阳时", "文档"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-BAZI-PILLARS-01",
    surfaces: ["report/cover", "report/structure", "bazi/hub"],
    role: "structure",
    title: "四柱：年月日时",
    caption: "四柱各有分工，日主居中",
    alt: "八字四柱结构教学图",
    filename: "bazi-four-pillars.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Four vertical pillar cards labeled 年柱 月柱 日柱 时柱 with 日主 highlighted on day pillar. Clean educational Chinese metaphysics chart, soft paper, ink blue accents, geometric, textbook clarity.",
    reportCiteKeys: ["structure", "cover"],
    tags: ["四柱", "八字"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-DAYUN-GRID-01",
    surfaces: ["report/timing", "dimensions/fortune-rhythm"],
    role: "timing",
    title: "大运网格怎么看",
    caption: "十年一段，关注交接与主题切换",
    alt: "大运十年网格阅读示意图",
    filename: "dayun-decade-grid.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Horizontal decade grid of life stages 大运 with one cell highlighted 当前大运 and small markers for year changes. Minimal table aesthetic, Chinese labels, educational, soft paper background.",
    reportCiteKeys: ["dayun"],
    tags: ["大运", "网格"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-TOOL-RESULT-01",
    surfaces: ["tools/result", "tools/hub"],
    role: "action",
    title: "工具结果：下一步",
    caption: "看主题结论 → 升级完整报告 → 问老师",
    alt: "工具结果页下一步路径图",
    filename: "tool-result-next-steps.jpg",
    aspectRatio: "16:9",
    complexity: "complex",
    prompt:
      "Three next-step cards after a tool result: 理解主题结论, 生成完整报告, 问顾问老师. Arrows between them, Linear product UI, Chinese labels, calm paper background.",
    reportCiteKeys: [],
    tags: ["工具", "转化"],
    ready: true,
    width: 1600,
    height: 900,
  },
  {
    id: "PI-ICON-OVERVIEW",
    surfaces: ["teachers/overview", "icon/teachers"],
    role: "summary",
    title: "总览老师",
    caption: "全局结构与优先级",
    alt: "总览老师图标",
    filename: "icon-teacher-overview.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square app icon: abstract compass or overview grid, muted ink blue on soft paper, minimal geometric, label 总览 small Chinese text optional, no face, Linear style icon.",
    reportCiteKeys: [],
    tags: ["icon", "老师"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-CAREER",
    surfaces: ["teachers/career", "icon/teachers"],
    role: "summary",
    title: "事业老师",
    caption: "岗位与阶段动作",
    alt: "事业老师图标",
    filename: "icon-teacher-career.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: minimal briefcase or building geometric mark, ink blue, soft paper, Chinese optional 事业, Linear product icon, no face.",
    reportCiteKeys: [],
    tags: ["icon", "事业"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-WEALTH",
    surfaces: ["teachers/wealth", "icon/teachers"],
    role: "summary",
    title: "财务老师",
    caption: "现金流与配置节奏",
    alt: "财务老师图标",
    filename: "icon-teacher-wealth.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: minimal coin stack or ledger geometric, muted blue-green, soft paper, optional 财务, Linear icon, no luxury bling, no face.",
    reportCiteKeys: [],
    tags: ["icon", "财务"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-RELATION",
    surfaces: ["teachers/relationship", "icon/teachers"],
    role: "summary",
    title: "关系老师",
    caption: "互动边界与节奏",
    alt: "关系老师图标",
    filename: "icon-teacher-relationship.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: two geometric nodes connected by soft line, ink blue, soft paper, optional 关系, Linear, no faces, not romantic stock.",
    reportCiteKeys: [],
    tags: ["icon", "关系"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-TIMING",
    surfaces: ["teachers/timing", "icon/teachers"],
    role: "summary",
    title: "时机老师",
    caption: "窗口与先后次序",
    alt: "时机老师图标",
    filename: "icon-teacher-timing.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: minimal clock or calendar window, ink blue, soft paper, optional 时机, Linear product icon.",
    reportCiteKeys: [],
    tags: ["icon", "时机"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-HEALTH",
    surfaces: ["teachers/health", "icon/teachers"],
    role: "summary",
    title: "节律老师",
    caption: "身心节奏与恢复",
    alt: "节律老师图标",
    filename: "icon-teacher-health.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: gentle waveform or leaf geometric for life rhythm, soft green-blue, paper background, optional 节律, Linear, not medical cross spam.",
    reportCiteKeys: [],
    tags: ["icon", "节律"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-PRACTICE",
    surfaces: ["teachers/practice", "icon/teachers"],
    role: "summary",
    title: "实践老师",
    caption: "落地动作与复盘",
    alt: "实践老师图标",
    filename: "icon-teacher-practice.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: checklist with one checkmark geometric, ink blue, soft paper, optional 实践, Linear product icon.",
    reportCiteKeys: [],
    tags: ["icon", "实践"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-GEO",
    surfaces: ["teachers/geo", "icon/teachers", "movement/hub"],
    role: "summary",
    title: "地理老师",
    caption: "环境与迁移观察",
    alt: "地理老师图标",
    filename: "icon-teacher-geo.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: minimal map pin over soft globe arc, ink blue, paper background, optional 地理, Linear icon.",
    reportCiteKeys: [],
    tags: ["icon", "地理"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-VERIFY",
    surfaces: ["events/validation", "icon/actions"],
    role: "action",
    title: "验证",
    caption: "对照现实",
    alt: "验证动作图标",
    filename: "icon-action-verify.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: check circle geometric, soft green-blue, paper, optional 验证, Linear.",
    reportCiteKeys: [],
    tags: ["icon", "验证"],
    ready: true,
    width: 1024,
    height: 1024,
  },
  {
    id: "PI-ICON-BOUNDARY",
    surfaces: ["boundary/not-fatalism", "icon/actions"],
    role: "risk",
    title: "边界",
    caption: "参考不是定论",
    alt: "判断边界图标",
    filename: "icon-action-boundary.jpg",
    aspectRatio: "1:1",
    complexity: "simple",
    prompt:
      "Simple square icon: soft shield or dashed boundary box, amber-blue muted, paper, optional 边界, Linear, calm not alarming.",
    reportCiteKeys: [],
    tags: ["icon", "边界"],
    ready: true,
    width: 1024,
    height: 1024,
  },
];

export function buildFullPrompt(entry: PageIllustrationEntry): string {
  return `${entry.prompt}\n\n${PAGE_ILLUST_STYLE_SUFFIX}\nAspect ${entry.aspectRatio}.`;
}

export function publicSrc(entry: PageIllustrationEntry): string {
  return `/images/page-illustrations/${entry.filename}`;
}

export function listBySurface(surface: string): PageIllustrationEntry[] {
  return PAGE_ILLUSTRATION_CATALOG.filter((e) => e.surfaces.includes(surface));
}

export function listByReportKeys(keys: string[]): PageIllustrationEntry[] {
  const set = new Set(keys);
  return PAGE_ILLUSTRATION_CATALOG.filter((e) =>
    (e.reportCiteKeys || []).some((k) => set.has(k)),
  );
}
