import type { RightsStatus } from '@/lib/knowledge-taxonomy';

export type DomainKey =
  | 'metaphysics'
  | 'psychology'
  | 'philosophy'
  | 'history'
  | 'programming'
  | 'ai'
  | 'statistics'
  | 'astrology'
  | 'medicine'
  | 'law';
export type AcquisitionMethod = 'rss' | 'web' | 'bb-site' | 'manual' | 'api';
export type AcquisitionTier = 'P0' | 'P1' | 'P2' | 'P3';
export type SourceRole = 'authority' | 'catalog' | 'community' | 'trend' | 'supplement';
export type ProductFit = 'core' | 'adjacent' | 'exploratory';

export interface DomainSourcePreset {
  id: string;
  label: string;
  domain: DomainKey;
  tier: AcquisitionTier;
  role: SourceRole;
  method: AcquisitionMethod;
  platform: string;
  url: string;
  rightsStatus: RightsStatus;
  productFit: ProductFit;
  productRelevance: number;
  relatedUseCases: string[];
  acquisitionGoal: string[];
  extractionTargets: string[];
  notes: string;
  fitNotes: string;
}

export interface DomainKnowledgeChain {
  domain: DomainKey;
  title: string;
  coreObjects: string[];
  primaryGoals: string[];
  acquisitionOrder: AcquisitionTier[];
}

const DOMAIN_PRIORITY: Record<DomainKey, number> = {
  metaphysics: 100,
  psychology: 92,
  philosophy: 90,
  history: 84,
  ai: 82,
  statistics: 80,
  programming: 76,
  astrology: 72,
  medicine: 70,
  law: 40,
};

export const DOMAIN_KNOWLEDGE_CHAINS: DomainKnowledgeChain[] = [
  {
    domain: 'metaphysics',
    title: '玄学 / 命理 / 易学',
    coreObjects: ['source_document', 'book', 'concept', 'school', 'question', 'topic', 'case'],
    primaryGoals: ['公版经典骨架', '书目体系', '流派比较', '问题地图', '参考智能'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'psychology',
    title: '心理学',
    coreObjects: ['source_document', 'book', 'concept', 'question', 'topic'],
    primaryGoals: ['心理术语归一', '情绪与压力表达', '关系和行为解释辅助'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'philosophy',
    title: '哲学',
    coreObjects: ['source_document', 'book', 'concept', 'person', 'question', 'topic'],
    primaryGoals: ['概念澄清', '方法论强化', '世界观与认识论支撑'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'history',
    title: '历史学',
    coreObjects: ['source_document', 'book', 'person', 'question', 'topic'],
    primaryGoals: ['历史语境', '思想史脉络', '案例时间线'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'programming',
    title: '程序 / 软件工程',
    coreObjects: ['source_document', 'concept', 'question', 'topic'],
    primaryGoals: ['工程方法论', '系统实现参考', '工具文档骨架'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'ai',
    title: 'AI / 机器学习',
    coreObjects: ['source_document', 'book', 'concept', 'question', 'topic'],
    primaryGoals: ['模型方法论', 'Agent 系统参考', '知识引擎实现参考'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'statistics',
    title: '统计学',
    coreObjects: ['source_document', 'book', 'concept', 'question', 'topic'],
    primaryGoals: ['验证框架', '不确定性表达', '评分与校准方法'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'astrology',
    title: '星座学 / 西方占星',
    coreObjects: ['source_document', 'book', 'concept', 'school', 'question', 'topic'],
    primaryGoals: ['星座学书目', '术语映射', '与命理对照问题', '用户兴趣入口'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'medicine',
    title: '医学 / 健康参考',
    coreObjects: ['source_document', 'book', 'concept', 'question', 'topic'],
    primaryGoals: ['健康边界说明', '症状语言校正', '风险提示语料', '循证参考入口'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
  {
    domain: 'law',
    title: '法律',
    coreObjects: ['source_document', 'statute', 'case_rule', 'case_document', 'book', 'question', 'topic'],
    primaryGoals: ['官方法源骨架', '案例规则抽取', '书目索引', '问题综述', '参考智能'],
    acquisitionOrder: ['P0', 'P1', 'P2', 'P3'],
  },
];

export const DOMAIN_SOURCE_PRESETS: DomainSourcePreset[] = [
  {
    id: 'meta-ctext',
    label: 'Chinese Text Project',
    domain: 'metaphysics',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'ctext',
    url: 'https://ctext.org/',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 98,
    relatedUseCases: ['经典出处', '概念词典', '流派源头', '引用定位'],
    acquisitionGoal: ['古籍索引', '章节定位', '出处映射'],
    extractionTargets: ['title', 'section', 'canonical_url', 'summary', 'book_reference'],
    notes: '优先用于公版经典定位与引用，不直接假定可全量再发布。',
    fitNotes: '最适合作为命理和易学经典层的骨架源。',
  },
  {
    id: 'meta-wikisource',
    label: '中文维基文库',
    domain: 'metaphysics',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'wikisource',
    url: 'https://zh.wikisource.org/',
    rightsStatus: 'open_license',
    productFit: 'core',
    productRelevance: 92,
    relatedUseCases: ['公版文本', '开放许可引用', '古籍导读'],
    acquisitionGoal: ['公版文本', '开放许可引文'],
    extractionTargets: ['title', 'canonical_url', 'summary', 'license'],
    notes: '适合开放许可文本，但要保留许可信息。',
    fitNotes: '适合作为可公开引用的命理相关古籍文本层。',
  },
  {
    id: 'meta-openlibrary',
    label: 'Open Library',
    domain: 'metaphysics',
    tier: 'P1',
    role: 'catalog',
    method: 'web',
    platform: 'openlibrary',
    url: 'https://openlibrary.org/',
    rightsStatus: 'open_license',
    productFit: 'core',
    productRelevance: 88,
    relatedUseCases: ['命理书目', '版本比较', '学习路径'],
    acquisitionGoal: ['书目元数据', '版本信息'],
    extractionTargets: ['title', 'author', 'publisher', 'edition', 'isbn'],
    notes: '主要用于书目层，不作为全文来源。',
    fitNotes: '适合作为命理、易学和玄学书单的元数据源。',
  },
  {
    id: 'meta-zhihu',
    label: '知乎搜索',
    domain: 'metaphysics',
    tier: 'P2',
    role: 'community',
    method: 'bb-site',
    platform: 'zhihu',
    url: 'https://www.zhihu.com/search',
    rightsStatus: 'platform_restricted',
    productFit: 'core',
    productRelevance: 86,
    relatedUseCases: ['高频问题', '争议问题', '用户表达', '选题发现'],
    acquisitionGoal: ['高频问题', '争议点', '用户表达'],
    extractionTargets: ['question', 'title', 'url', 'author', 'summary', 'tags'],
    notes: '只做问题映射和摘要，不复刻回答全文。',
    fitNotes: '适合建立命理问题地图和真实用户表达层。',
  },
  {
    id: 'meta-bilibili',
    label: 'B站搜索',
    domain: 'metaphysics',
    tier: 'P2',
    role: 'community',
    method: 'bb-site',
    platform: 'bilibili',
    url: 'https://search.bilibili.com/',
    rightsStatus: 'platform_restricted',
    productFit: 'core',
    productRelevance: 83,
    relatedUseCases: ['入门课程', '书单信号', '评论问题', '流派热点'],
    acquisitionGoal: ['入门视频', '书单信号', '问题热度'],
    extractionTargets: ['title', 'url', 'author', 'summary', 'comment_topics'],
    notes: '适合做话题发现，不适合镜像视频内容。',
    fitNotes: '适合沉淀课程型入口和用户评论问题。',
  },
  {
    id: 'psych-nimh',
    label: 'NIMH',
    domain: 'psychology',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'nimh',
    url: 'https://www.nimh.nih.gov/',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 89,
    relatedUseCases: ['心理健康边界', '情绪和压力术语', '安全提示'],
    acquisitionGoal: ['官方心理健康资料', '症状表达边界', '风险提示'],
    extractionTargets: ['title', 'condition', 'summary', 'warning_signs', 'canonical_url'],
    notes: '适合作为情绪、压力、焦虑等表达的权威边界层。',
    fitNotes: '和命理产品高度相关，能明显提升关系与健康板块的安全性。',
  },
  {
    id: 'psych-apa-dictionary',
    label: 'APA Dictionary of Psychology',
    domain: 'psychology',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'apa',
    url: 'https://dictionary.apa.org/',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 85,
    relatedUseCases: ['心理术语归一', '概念解释', '用户表达清洗'],
    acquisitionGoal: ['心理学术语标准化', '概念释义'],
    extractionTargets: ['term', 'definition', 'canonical_url'],
    notes: '适合作为心理术语层，不适合作为全文内容抓取层。',
    fitNotes: '可直接用于情绪、关系和行为相关术语的规范化。',
  },
  {
    id: 'phil-sep',
    label: 'Stanford Encyclopedia of Philosophy',
    domain: 'philosophy',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'sep',
    url: 'https://plato.stanford.edu/',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 88,
    relatedUseCases: ['方法论支撑', '概念澄清', '认识论框架'],
    acquisitionGoal: ['哲学概念骨架', '学术词条', '方法论背景'],
    extractionTargets: ['title', 'author', 'summary', 'canonical_url', 'topic'],
    notes: '适合作为哲学概念和方法论参考层。',
    fitNotes: '最适合强化命理产品的解释边界、认识论和方法论表达。',
  },
  {
    id: 'phil-iep',
    label: 'Internet Encyclopedia of Philosophy',
    domain: 'philosophy',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'iep',
    url: 'https://iep.utm.edu/',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 82,
    relatedUseCases: ['哲学词条', '历史人物', '概念延展'],
    acquisitionGoal: ['哲学概念补充', '人物和主题索引'],
    extractionTargets: ['title', 'author', 'summary', 'canonical_url'],
    notes: '适合作为 SEP 的补充参考层。',
    fitNotes: '适合构建概念对照和历史思想脉络。',
  },
  {
    id: 'hist-office-historian',
    label: 'Office of the Historian',
    domain: 'history',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'history-state-gov',
    url: 'https://history.state.gov/',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 78,
    relatedUseCases: ['历史语境', '思想脉络', '时间线方法'],
    acquisitionGoal: ['官方历史档案', '主题时间线', '历史语境'],
    extractionTargets: ['title', 'timeline', 'summary', 'canonical_url'],
    notes: '适合作为时间线和制度史的参考方法层。',
    fitNotes: '适合帮助产品建立“历史语境 + 时间线”解释结构。',
  },
  {
    id: 'hist-loc',
    label: 'Library of Congress Digital Collections',
    domain: 'history',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'loc',
    url: 'https://www.loc.gov/collections/',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 74,
    relatedUseCases: ['史料索引', '历史语义', '主题档案'],
    acquisitionGoal: ['数字史料索引', '主题历史资料'],
    extractionTargets: ['title', 'collection', 'summary', 'canonical_url'],
    notes: '适合作为主题史料和历史资料索引层。',
    fitNotes: '适合做历史背景和文化语境层，而非主判断层。',
  },
  {
    id: 'prog-python-docs',
    label: 'Python Documentation',
    domain: 'programming',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'python-docs',
    url: 'https://docs.python.org/3/',
    rightsStatus: 'open_license',
    productFit: 'adjacent',
    productRelevance: 79,
    relatedUseCases: ['脚本开发', '数据处理', '采集工具实现'],
    acquisitionGoal: ['官方语言参考', '实现细节', '脚本能力'],
    extractionTargets: ['title', 'section', 'summary', 'canonical_url'],
    notes: '适合作为内部工程与数据工具实现参考。',
    fitNotes: '和资料引擎的自动化、清洗、分析实现直接相关。',
  },
  {
    id: 'prog-mdn',
    label: 'MDN Web Docs',
    domain: 'programming',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'mdn',
    url: 'https://developer.mozilla.org/en-US/docs/MDN',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 73,
    relatedUseCases: ['前端实现', '浏览器能力', '抓取适配'],
    acquisitionGoal: ['Web 平台文档', '前端实现参考', '浏览器 API 说明'],
    extractionTargets: ['title', 'guide', 'summary', 'canonical_url'],
    notes: '适合作为前端和浏览器能力参考。',
    fitNotes: '对浏览器适配、bb-browser 类能力和前端产品实现有直接帮助。',
  },
  {
    id: 'ai-arxiv',
    label: 'arXiv',
    domain: 'ai',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'arxiv',
    url: 'https://arxiv.org/',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 84,
    relatedUseCases: ['Agent 方法', 'RAG', '知识图谱', '信息抽取', '评价方法'],
    acquisitionGoal: ['AI 论文索引', '方法演进', '一手研究'],
    extractionTargets: ['title', 'authors', 'abstract_summary', 'category', 'canonical_url'],
    notes: '适合作为 AI 方法和知识引擎实现的一手研究索引。',
    fitNotes: '对资料引擎、Agent、RAG、知识图谱和评价体系都高度相关。',
  },
  {
    id: 'ai-openreview',
    label: 'OpenReview',
    domain: 'ai',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'openreview',
    url: 'https://openreview.net/about',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 81,
    relatedUseCases: ['前沿论文', '同行评审语境', '研究趋势'],
    acquisitionGoal: ['开放评审论文', '前沿研究上下文', '趋势观察'],
    extractionTargets: ['title', 'authors', 'abstract_summary', 'venue', 'canonical_url'],
    notes: '适合作为 AI 前沿研究和开放评审上下文层。',
    fitNotes: '适合帮助我们理解当前 Agent 和 AI 系统研究的前沿语境。',
  },
  {
    id: 'stats-nist',
    label: 'NIST e-Handbook of Statistical Methods',
    domain: 'statistics',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'nist',
    url: 'https://www.nist.gov/programs-projects/nistsematech-engineering-statistics-handbook',
    rightsStatus: 'unknown',
    productFit: 'core',
    productRelevance: 84,
    relatedUseCases: ['校准方法', '实验设计', '不确定性表达', '质量控制'],
    acquisitionGoal: ['统计方法骨架', '实验设计', '质量与置信度方法'],
    extractionTargets: ['title', 'topic', 'summary', 'canonical_url'],
    notes: '适合作为统计方法和验证框架的骨架源。',
    fitNotes: '对模型评分、状态向量校准和验证闭环非常有帮助。',
  },
  {
    id: 'stats-openintro',
    label: 'OpenIntro Statistics',
    domain: 'statistics',
    tier: 'P1',
    role: 'catalog',
    method: 'web',
    platform: 'openintro',
    url: 'https://www.openintro.org/book/os/',
    rightsStatus: 'open_license',
    productFit: 'core',
    productRelevance: 78,
    relatedUseCases: ['统计入门', '概念解释', '教育型内容'],
    acquisitionGoal: ['统计教材和概念', '开放许可教育资源'],
    extractionTargets: ['title', 'topic', 'summary', 'canonical_url', 'license'],
    notes: '开放许可清晰，适合教学和概念说明层。',
    fitNotes: '适合把统计概念翻译成产品可理解的解释层。',
  },
  {
    id: 'astro-astrodatabank',
    label: 'Astro-Databank',
    domain: 'astrology',
    tier: 'P0',
    role: 'catalog',
    method: 'web',
    platform: 'astro-databank',
    url: 'https://www.astro.com/astro-databank/Main_Page',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 74,
    relatedUseCases: ['星座学术语', '人物案例', '西方占星入口'],
    acquisitionGoal: ['人物资料索引', '星座学案例', '术语映射'],
    extractionTargets: ['title', 'person_name', 'birth_data', 'topic_tag', 'canonical_url'],
    notes: '适合作为西方占星资料索引，不适合直接复用全文内容。',
    fitNotes: '适合作为命理产品的对照兴趣层，不是核心判断底盘。',
  },
  {
    id: 'astro-openlibrary',
    label: 'Open Library Astrology Catalog',
    domain: 'astrology',
    tier: 'P1',
    role: 'catalog',
    method: 'web',
    platform: 'openlibrary',
    url: 'https://openlibrary.org/subjects/astrology',
    rightsStatus: 'open_license',
    productFit: 'adjacent',
    productRelevance: 78,
    relatedUseCases: ['星座书单', '西方占星入门路径', '概念对照'],
    acquisitionGoal: ['占星书目', '主题分类', '版本信息'],
    extractionTargets: ['title', 'author', 'subject', 'edition', 'canonical_url'],
    notes: '主要用于书目和入门路径层。',
    fitNotes: '适合把西方占星作为扩展兴趣面，而不是产品核心引擎来源。',
  },
  {
    id: 'astro-youtube',
    label: 'YouTube Astrology Search',
    domain: 'astrology',
    tier: 'P2',
    role: 'community',
    method: 'bb-site',
    platform: 'youtube',
    url: 'https://www.youtube.com/results',
    rightsStatus: 'platform_restricted',
    productFit: 'adjacent',
    productRelevance: 65,
    relatedUseCases: ['兴趣入口', '热点话题', '英文问题语料'],
    acquisitionGoal: ['占星热点', '视频主题', '评论问题'],
    extractionTargets: ['title', 'url', 'channel', 'summary', 'comment_topics'],
    notes: '适合作为英文世界兴趣与问题发现层。',
    fitNotes: '适合补足英文问题表达，不适合作为知识真源。',
  },
  {
    id: 'med-who-traditional',
    label: 'WHO Traditional, Complementary and Integrative Medicine',
    domain: 'medicine',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'who',
    url: 'https://www.who.int/teams/integrated-health-services/traditional-complementary-and-integrative-medicine',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 72,
    relatedUseCases: ['健康边界', '传统医学政策背景', '风险表述'],
    acquisitionGoal: ['官方健康背景', '传统医学政策', '边界说明'],
    extractionTargets: ['title', 'policy_summary', 'canonical_url', 'published_at'],
    notes: '适合作为传统医学和健康边界的官方背景层。',
    fitNotes: '适合帮助产品建立健康表达边界，不用于替代医学建议。',
  },
  {
    id: 'med-nccih',
    label: 'NCCIH',
    domain: 'medicine',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'nccih',
    url: 'https://www.nccih.nih.gov/',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 84,
    relatedUseCases: ['补充医学边界', '安全提示', '风险表述'],
    acquisitionGoal: ['循证补充医学资料', '安全性边界', '风险提示'],
    extractionTargets: ['title', 'summary', 'condition', 'safety_notes', 'canonical_url'],
    notes: '适合作为健康相关表述的边界和风险说明来源。',
    fitNotes: '和命理产品最相关的用途是建立健康板块的安全措辞，不是做诊断。',
  },
  {
    id: 'med-medlineplus',
    label: 'MedlinePlus',
    domain: 'medicine',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'medlineplus',
    url: 'https://medlineplus.gov/',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 80,
    relatedUseCases: ['症状术语', '健康科普', '医学名词校正'],
    acquisitionGoal: ['症状术语标准化', '健康问题解释', '用户语言映射'],
    extractionTargets: ['title', 'symptom', 'condition', 'summary', 'canonical_url'],
    notes: '适合做症状语言和健康话题的科普归一。',
    fitNotes: '适合把用户的健康表达规范化，避免使用误导性语言。',
  },
  {
    id: 'med-pubmed',
    label: 'PubMed',
    domain: 'medicine',
    tier: 'P1',
    role: 'catalog',
    method: 'web',
    platform: 'pubmed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/',
    rightsStatus: 'unknown',
    productFit: 'exploratory',
    productRelevance: 58,
    relatedUseCases: ['研究索引', '证据核验', '健康话题补证'],
    acquisitionGoal: ['医学研究索引', '循证补证', '主题证据线索'],
    extractionTargets: ['title', 'authors', 'abstract_summary', 'published_at', 'canonical_url'],
    notes: '适合研究索引和补证，不适合直接进内容发布链。',
    fitNotes: '只适合在健康边界和安全提示上做证据补强。',
  },
  {
    id: 'med-ncbi-bookshelf',
    label: 'NCBI Bookshelf',
    domain: 'medicine',
    tier: 'P1',
    role: 'catalog',
    method: 'web',
    platform: 'ncbi-bookshelf',
    url: 'https://www.ncbi.nlm.nih.gov/books/',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 66,
    relatedUseCases: ['健康知识路径', '公开医学参考书'],
    acquisitionGoal: ['公开医学书籍', '专业参考路径'],
    extractionTargets: ['title', 'author', 'section', 'summary', 'canonical_url'],
    notes: '适合作为公开医学参考书目和章节索引。',
    fitNotes: '适合做健康边界知识页和术语页，不适合进诊断链。',
  },
  {
    id: 'law-npc-flk',
    label: '国家法律法规数据库',
    domain: 'law',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'npc-flk',
    url: 'https://flk.npc.gov.cn/',
    rightsStatus: 'unknown',
    productFit: 'adjacent',
    productRelevance: 36,
    relatedUseCases: ['合规边界', '法条骨架', '政策时间线'],
    acquisitionGoal: ['法源骨架', '法条索引', '效力状态'],
    extractionTargets: ['title', 'organ', 'doc_number', 'published_at', 'effective_at', 'status', 'canonical_url'],
    notes: '法律域最核心骨架源之一。',
    fitNotes: '当前只保留为合规和未来独立域储备。',
  },
  {
    id: 'law-gov-policy',
    label: '中国政府网法规政策',
    domain: 'law',
    tier: 'P0',
    role: 'authority',
    method: 'web',
    platform: 'gov-cn',
    url: 'https://www.gov.cn/zhengce/xxgk/fggw/',
    rightsStatus: 'unknown',
    productFit: 'exploratory',
    productRelevance: 30,
    relatedUseCases: ['政策背景', '监管环境'],
    acquisitionGoal: ['法规政策补全', '政策时间线'],
    extractionTargets: ['title', 'organ', 'published_at', 'summary', 'canonical_url'],
    notes: '用于补足国务院和部委层面的政策规范文件。',
    fitNotes: '当前优先级明显低于其他相邻领域。',
  },
];

export function getDomainKnowledgeChain(domain: DomainKey) {
  return DOMAIN_KNOWLEDGE_CHAINS.find((item) => item.domain === domain) || null;
}

export function getDomainSourcePresets(domain: DomainKey) {
  return DOMAIN_SOURCE_PRESETS
    .filter((item) => item.domain === domain)
    .sort((left, right) => left.tier.localeCompare(right.tier) || right.productRelevance - left.productRelevance || left.label.localeCompare(right.label));
}

export function getProductRelevantSourcePresets(params?: {
  domains?: DomainKey[];
  minRelevance?: number;
  includeExploratory?: boolean;
  limit?: number;
}) {
  const domains = params?.domains || [
    'metaphysics',
    'psychology',
    'philosophy',
    'history',
    'ai',
    'statistics',
    'programming',
    'astrology',
    'medicine',
    'law',
  ];
  const minRelevance = params?.minRelevance ?? 60;
  const includeExploratory = params?.includeExploratory ?? false;
  const limit = params?.limit ?? 24;

  return DOMAIN_SOURCE_PRESETS
    .filter((item) => domains.includes(item.domain))
    .filter((item) => item.productRelevance >= minRelevance)
    .filter((item) => includeExploratory || item.productFit !== 'exploratory')
    .sort((left, right) => (
      (DOMAIN_PRIORITY[right.domain] + right.productRelevance) - (DOMAIN_PRIORITY[left.domain] + left.productRelevance)
      || left.tier.localeCompare(right.tier)
    ))
    .slice(0, limit);
}

export function getCoreReferenceSourcePresets(limit = 18) {
  return getProductRelevantSourcePresets({
    domains: ['metaphysics', 'psychology', 'philosophy', 'history', 'ai', 'statistics', 'programming', 'astrology', 'medicine'],
    minRelevance: 72,
    includeExploratory: false,
    limit,
  });
}
