/**
 * 双轨埋点事件白名单（服务端 funnel / analytics 共用）
 */

export const PRODUCT_FUNNEL_EVENTS = [
  // mass
  'mass_report_viewed',
  'mass_decision_copied',
  'mass_decision_printed',
  'mass_revisit_marked',
  'mass_prediction_seed_shown',
  'mass_prediction_outcome',
  'mass_prediction_to_event',
  'mass_need_map_click',
  'mass_action_bar_viewed',
  'mass_learn_path_click',
  'mass_teacher_open',
  'teachers_page_viewed',
  'mass_profile_field_saved',
  'mass_profile_field_skipped',
  // loop
  'hehun_page_viewed',
  'hehun_run',
  'hehun_prefill_used',
  'events_page_viewed',
  'events_created',
  'events_feedback',
  'chat_page_viewed',
  'chat_message_sent',
  'chat_anchor_loaded',
  'timing_window_viewed',
  // expert
  'expert_view_opened',
  'expert_handoff_copied',
  'expert_print_clicked',
  'expert_crm_saved',
  'expert_crm_script_copied',
  'expert_crm_desk_viewed',
  'expert_dayun_grid_viewed',
  // entry
  'tool_entry_clicked',
  'portal_rail_clicked',
  // legacy funnel kept for compatibility
  'home_page_view',
  'home_report_click',
  'home_membership_click',
  'report_page_view',
  'report_generate_click',
  'report_generated',
  'report_generate_failed',
  'report_email_started',
  'report_email_saved',
  'report_membership_click',
  'membership_page_view',
  'membership_email_prefill',
  'membership_checkout_click',
  'membership_activated',
  'chat_to_analyze_click',
] as const;

export type FunnelEventName = (typeof PRODUCT_FUNNEL_EVENTS)[number];

export const PRODUCT_ANALYTICS_EXTRA_EVENTS = [
  'mass_report_viewed',
  'mass_decision_copied',
  'mass_decision_printed',
  'mass_revisit_marked',
  'mass_prediction_seed_shown',
  'mass_prediction_outcome',
  'mass_prediction_to_event',
  'mass_need_map_click',
  'mass_learn_path_click',
  'mass_teacher_open',
  'teachers_page_viewed',
  'mass_profile_field_saved',
  'mass_profile_field_skipped',
  'hehun_page_viewed',
  'hehun_run',
  'hehun_prefill_used',
  'events_created',
  'events_feedback',
  'chat_message_sent',
  'chat_anchor_loaded',
  'timing_window_viewed',
  'expert_view_opened',
  'expert_handoff_copied',
  'expert_print_clicked',
  'expert_crm_saved',
  'expert_crm_script_copied',
  'expert_crm_desk_viewed',
  'expert_dayun_grid_viewed',
  'tool_entry_clicked',
  'portal_rail_clicked',
  'predictions_page_viewed',
  'hehun_workspace_viewed',
  'expert_crm_page_viewed',
] as const;
